# docker-compose.yml

version: "3.9"

services:
  scraper:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - 8001:8001
    depends_on:
      - mongoservice
    networks:
      - backendnetwork

  mongoservice:
    image: mongo:latest
    restart: always
    ports:
      - 27017:27017
    environment:
      MONGO_INITDB_ROOT_USERNAME: "${MONGODB_DB_USERNAME}"
      MONGO_INITDB_ROOT_PASSWORD: "${MONGODB_DB_PASSWORD}"
      MONGO_INITDB_DATABASE: "${MONGODB_DB_NAME}"
    env_file:
      - .env
    volumes:
      - ./initdb.d/:/docker-entrypoint-initdb.d/
      - ./dbdata/mongo_data/data:/data/db/
    networks:
      - backendnetwork

networks:
  backendnetwork:
    external: true
